name = "test-agent-1"
number = 1

[web]

bind_address = "127.0.0.1"
port = 3030

[web.tls]

# Default paths that are initialized automatically.
private_key_path = "config/agent.key"
certificate_path = "config/agent.crt"

[dns]

# Cloudflare is currently the only supported provider for dns services.
provider="Cloudflare"
api_key="<ClOUDFLAREAPIKEY>"
domain="yourdomain.com"